package com.cleviro.ErpManagerApp.exception;

public enum EntityType {
    USER,
    ROLE,
    COMPANY,
    COUNTRY,
    DEPARTMENT,
    LOCATION,
    STORE,
    ZONE,
    CUSTOMER,
    CUSTOMERTYPE,
    DESIGNATION,
    EMPLOYEE,
    EMPLOYMENTTYPE,
    GENDER,
    SUPPLIER,
    SUPPLIERTYPE,
    SUPERVISOR,
    PAYER,
    VISIT,
    PAYERACCOUNT,
    SCHEME,
    PLAN,
    CONSULTATIONRATE,
    CONSULTATIONTYPE,
    COPAYCATEGORY,
    DEPARTMENTLIMIT,
    LIMITCATEGORY,
    PLANCATEGORY,
    SCHEMETYPE

}
